[project]
name = "wifi-presence-scanner"
requires-python = ">=3.13"
version = "0.1"
dependencies = [
    "python-dotenv",
    "lxml",
    "sqlmodel",
    "fastapi[standard]",
    "requests>=2.32.3",
]
